#修改server端口
server:
    port: 5050
    # context-path: /helloboot
spring:
    application:
      name: healthdemo

    redis:
#      host: 192.168.50.53
#      port: 6379
      host: 10.42.64.26
      port: 8083
      database: 2
      password:
      timeout: 1800000
      jedis:
        pool:
          max-idle: 10
          min-idle: 0
          max-active: 10
          max-wait: 1000

#sql日志
logging:
  level:
    com.kdcg.hand.mapper: DEBUG
  #eureka:
    #client:
      #serviceUrl:
      #defaultZone: http://localhost:8000/eureka

#数据源
#spring:
#datasource:
     # url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
     # username: root
     # password: root